version: "3"

includes:
  knative:
    taskfile: knative/Taskfile.yml
    dir: knative
  oauth2-proxy-mcp:
    taskfile: oauth2-proxy-mcp/Taskfile.yml
    dir: oauth2-proxy-mcp
  dapr:
    taskfile: dapr/Taskfile.yml
    dir: dapr
