{{- if .Values.apiKey.externalSecret.enabled -}}
apiVersion: {{ .Values.apiKey.externalSecret.apiVersion }}
kind: ExternalSecret
metadata:
  name: {{ include "adk-agent.fullname" . }}
  labels:
    {{- include "adk-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.apiKey.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    name: {{ .Values.apiKey.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.apiKey.externalSecret.secretStoreRef.kind }}
  target:
    # ESO will create / update this k8s Secret. The Deployment reads from it.
    name: {{ .Values.apiKey.existingSecret.name }}
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: {{ .Values.apiKey.existingSecret.key }}
      remoteRef:
        key: {{ .Values.apiKey.externalSecret.remoteRef.key | quote }}
        {{- with .Values.apiKey.externalSecret.remoteRef.property }}
        property: {{ . | quote }}
        {{- end }}
        {{- with .Values.apiKey.externalSecret.remoteRef.conversionStrategy }}
        conversionStrategy: {{ . }}
        {{- end }}
        {{- with .Values.apiKey.externalSecret.remoteRef.decodingStrategy }}
        decodingStrategy: {{ . }}
        {{- end }}
{{- end }}
