{{- include "adk-agent.validateApiKey" . -}}
{{- if .Values.apiKey.inline.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.apiKey.existingSecret.name }}
  labels:
    {{- include "adk-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.apiKey.existingSecret.key }}: {{ .Values.apiKey.inline.value | quote }}
{{- end }}
