{{- if .Values.secretstore.enabled }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ include "app.name" . }}-secretstore
  namespace: {{ include "app.namespace" . }}
spec:
  type: secretstores.hashicorp.vault
  version: v1
  metadata:
    - name: vaultAddr
      value: {{ .Values.secretstore.vault.address | quote }}
    - name: vaultToken
      secretKeyRef:
        name: {{ .Values.secretstore.vault.tokenSecret.name | quote }}
        key: {{ .Values.secretstore.vault.tokenSecret.key | quote }}
    - name: vaultKVPrefix
      value: "dapr"
    - name: enginePath
      value: "secret"
    - name: vaultValueType
      value: "map"
    - name: skipVerify
      value: "true"
scopes:
  - {{ include "app.name" . }}
{{- end }}
