apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server-watcher
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-server-watcher
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server-watcher
subjects:
  - kind: ServiceAccount
    name: api-server-watcher
    namespace: default
roleRef:
  kind: ClusterRole
  name: api-server-watcher
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: sources.knative.dev/v1
kind: ApiServerSource
metadata:
  name: pod-watcher
  namespace: default
spec:
  serviceAccountName: api-server-watcher
  mode: Resource
  resources:
    - apiVersion: v1
      kind: Pod
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: default
