---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    app.kubernetes.io/managed-by: flux
    # Knative needs to know it can route traffic into this namespace
    serving.knative.dev/release: "v1.22.0"
